set_property IOSTANDARD LVTTL [get_ports sys_clk_i]
set_property PACKAGE_PIN N11 [get_ports sys_clk_i]

set_property IOSTANDARD LVTTL [get_ports ext_rst_n]
set_property PACKAGE_PIN M2 [get_ports ext_rst_n]

set_property IOSTANDARD LVTTL [get_ports {dtube_cs_n[0]}]
set_property PACKAGE_PIN M12  [get_ports {dtube_cs_n[0]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_cs_n[1]}]
set_property PACKAGE_PIN P14  [get_ports {dtube_cs_n[1]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_cs_n[2]}]
set_property PACKAGE_PIN  N14 [get_ports {dtube_cs_n[2]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_cs_n[3]}]
set_property PACKAGE_PIN  N13 [get_ports {dtube_cs_n[3]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[0]}]
set_property PACKAGE_PIN N3  [get_ports {dtube_data[0]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[1]}]
set_property PACKAGE_PIN P3  [get_ports {dtube_data[1]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[2]}]
set_property PACKAGE_PIN M4  [get_ports {dtube_data[2]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[3]}]
set_property PACKAGE_PIN L4  [get_ports {dtube_data[3]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[4]}]
set_property PACKAGE_PIN R11  [get_ports {dtube_data[4]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[5]}]
set_property PACKAGE_PIN N4  [get_ports {dtube_data[5]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[6]}]
set_property PACKAGE_PIN M5  [get_ports {dtube_data[6]}]
set_property IOSTANDARD LVTTL [get_ports {dtube_data[7]}]
set_property PACKAGE_PIN L5  [get_ports {dtube_data[7]}]
 
